In [97]:
1+1


2

In [98]:
##numpy
import numpy as np

In [99]:
lst=[1,2,3,4]
arr=np.array(lst)

In [100]:
arr

array([1, 2, 3, 4])

In [101]:
type(arr)


numpy.ndarray

In [102]:
arr.shape

(4,)

In [103]:
arr1=np.array([[1,6,3],[5,9,8]])

In [104]:
arr1

array([[1, 6, 3],
       [5, 9, 8]])

In [105]:
arr1.shape

(2, 3)

In [106]:
arr1.reshape(3,2)

array([[1, 6],
       [3, 5],
       [9, 8]])

In [107]:
arr1.dtype

dtype('int32')

In [108]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [110]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [111]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [112]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [113]:
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [114]:
arr2=np.zeros((3,4))

In [115]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [116]:
type(arr1)

numpy.ndarray

In [117]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [118]:
arr2=np.array([[[5,2,8],[2,5,7]]])

In [119]:
arr2

array([[[5, 2, 8],
        [2, 5, 7]]])

In [120]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [121]:
5+np.ones((5,2,8))

array([[[6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.]],

       [[6., 6., 6., 6., 6., 6., 6., 6.],
        [6., 6., 6., 6., 6., 6., 6., 6.]]])

In [122]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [123]:
np.eye(6).reshape(12,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [124]:
##uniform distribution
np.random.rand(2,3)

array([[0.67324932, 0.28503658, 0.37707616],
       [0.34986991, 0.35452098, 0.53842488]])

In [125]:
##normal distribution
np.random.rand(2,3)

array([[0.9659737 , 0.92780259, 0.12181665],
       [0.04694062, 0.13518516, 0.76418822]])

In [126]:
##random number
np.random.randint(1,100)

70

In [127]:
np.random.randint(1,100,5)

array([70, 79, 67, 62, 20])

In [128]:
## for creating array in random number
np.random.randint(1,500,(5,9))

array([[402, 299, 479, 340, 215, 190, 491, 377, 444],
       [469, 370, 425, 281, 274,  93,   2, 203, 422],
       [320, 235, 429, 290, 228, 360, 213, 338, 164],
       [120, 405,  50, 213,  41, 158, 489, 400, 262],
       [137, 255, 109, 491, 347, 163, 271,  14, 479]])

In [129]:
arr=np.arange(0,11)

In [130]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [131]:
arr[0]

0

In [132]:
arr[4]

4

In [133]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [135]:
arr[-1]

10

In [136]:
arr[-7]

4

In [137]:
arr[-1:7:-1]

array([10,  9,  8])

In [138]:
arr[-1:3]

array([], dtype=int32)

In [139]:
arr[-1:3:-2]

array([10,  8,  6,  4])

In [140]:
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])

In [141]:
arr1=np.random.randint(2,100,20).reshape(5,4)

In [142]:
arr1

array([[76, 65, 48, 52],
       [98, 86, 41, 72],
       [73, 57, 67, 21],
       [26, 10,  4, 78],
       [83,  6, 90, 14]])

In [143]:
arr1[0:3]

array([[76, 65, 48, 52],
       [98, 86, 41, 72],
       [73, 57, 67, 21]])

In [144]:
arr1[0:3,0:3]

array([[76, 65, 48],
       [98, 86, 41],
       [73, 57, 67]])

In [145]:
arr1[0:3]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ]

SyntaxError: unmatched ']' (1723045835.py, line 1)

In [146]:
arr1=np.random.randint(2,100,20).reshape(5,4)

In [147]:
arr1

array([[66, 18, 31, 47],
       [90, 84, 75, 90],
       [14, 99, 41, 30],
       [49, 22, 95, 30],
       [45, 58, 75, 69]])

In [154]:
arr1[3:,1:]    

array([[22, 95, 30],
       [58, 75, 69]])

In [155]:
arr1

array([[66, 18, 31, 47],
       [90, 84, 75, 90],
       [14, 99, 41, 30],
       [49, 22, 95, 30],
       [45, 58, 75, 69]])

In [176]:
arr1[2:4,1:3:]

array([[99, 41],
       [22, 95]])

In [193]:
##universal functions
arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(20,500,(3,3))

In [178]:
arr1

array([[44, 50, 27],
       [63,  8, 38],
       [34, 78, 14]])

In [179]:
arr2

array([[158,  77, 417],
       [168, 203, 210],
       [476, 371, 238]])

In [180]:
arr1+arr2

array([[202, 127, 444],
       [231, 211, 248],
       [510, 449, 252]])

In [181]:
arr1*arr2

array([[ 6952,  3850, 11259],
       [10584,  1624,  7980],
       [16184, 28938,  3332]])

In [182]:
arr1/arr2

array([[0.27848101, 0.64935065, 0.0647482 ],
       [0.375     , 0.03940887, 0.18095238],
       [0.07142857, 0.21024259, 0.05882353]])

In [184]:
np.sqrt(arr1+arr2)

array([[14.2126704 , 11.26942767, 21.07130751],
       [15.19868415, 14.52583905, 15.74801575],
       [22.58317958, 21.1896201 , 15.87450787]])

In [185]:
np.log10(arr1)

array([[1.64345268, 1.69897   , 1.43136376],
       [1.79934055, 0.90308999, 1.5797836 ],
       [1.53147892, 1.8920946 , 1.14612804]])

In [188]:
##Broadcasting
arr1=np.arange(1,10)

In [189]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [190]:
arr1[2:]=1000

In [191]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [194]:
np.matmul(arr1,arr2)

array([[30499, 30273, 37130],
       [54602, 65610, 67936],
       [44892, 47320, 45556]])